### ISSUE TITLE
<span><br/></span> does not work in FireFox

### ISSUE THREAD

**Issue by caasi** [ChineseCubes/react-odp#1]
FireFox:
![FireFox](https://cloud.githubusercontent.com/assets/1164470/3994225/5680e8e2-2917-11e4-8162-c8f2246bf08e.png)
Safari:
![Safari](https://cloud.githubusercontent.com/assets/1164470/3994224/567ce3dc-2917-11e4-820f-203e60ed5c35.png)

**Comment by audreyt** [comment]
Try something like:

``` css
br.draw.line-break { position: static }
```

**Comment by caasi** [comment]
FireFox:
![width-of-p](https://cloud.githubusercontent.com/assets/1164470/3998275/b1de2c84-2946-11e4-9fc3-d31fec035909.png)

`position: static` works for page 5, but introduces new problems at page 7 and 8.

I have not locate the cause yet.

**Comment by audreyt** [comment]
Try:

``` css
p.draw span { white-space: nowrap }
```
