### ISSUE TITLE
should set font family without calculate PostScript name in the script

### ISSUE THREAD

**Issue by caasi** [ChineseCubes/react-odp#5]
Currently I replace 'Noto Sans S Chinese Medium' with 'NotoSansHans-Medium'. See: https://github.com/ChineseCubes/react-odp/blob/448ddeb8219755e63c251f26cc298b82d9653ff5/src/CUBE/data.ls#L200

But it can be something like this:

``` css
@font-face {
  font-family: Noto Sans S Chinese Medium;
  src: local("Noto Sans S Chinese Medium"), 
       local("NotoSansHans-Medium"), 
       url(NotoHans-subset.ttf);
}
```

more info: https://hacks.mozilla.org/2009/06/beautiful-fonts-with-font-face/
